### ISSUE TITLE
Urthecast mismatch

### ISSUE THREAD

**Issue by apercas** [wri/gfw-api#241]
Hi, we're experiencing some failing tiles with the urthecast data set.

Right now these two tiles are different:
http://uc.gfw-apis.appspot.com/urthecast/map-tiles/rgb/3/4/3?cloud_coverage_lte=100&acquired_gte=2000-09-01T00:00:00Z&acquired_lte=2015-09-01T00:00:z00Z
https://tile-c.urthecast.com/v1/rgb/3/4/3?&api_key=###&api_secret=###&cloud_coverage_lte=100&acquired_gte=2000-09-01T00:00:00Z&acquired_lte=2015-09-01T00:00:z00Z

The first one doesn't seem to correspond with its zoom level (3) :(

**Comment by rashupee** [comment]
Hey Adrian, I don't know if this is because I am not looking very carefully
-  but when I switch between the two tiles, I can't tell any difference.
They appear the same to me. (I have them both open in my Mozilla browser
and am simply tabbing between the two.)

Fred

**Comment by d4weed** [comment]
That's really strange,
They were completely different yesterday (like the first one belonging to a
totally different zoom level)
We need to investigate what's going on here

On Mon, Oct 5, 2015 at 8:21 PM, rashupee < notifications@github.com > wrote:
Hey Adrian, I don't know if this is because I am not looking very carefully
- but when I switch between the two tiles, I can't tell any difference.
They appear the same to me. (I have them both open in my Mozilla browser
and am simply tabbing between the two.)

Fred

On Mon, Oct 5, 2015 at 9:44 AM, Adrián < notifications@github.com > wrote:

> Hi, we're experiencing some failing tiles with the urthecast data set.
>
> Right now these two tiles are different:
>
> http://uc.gfw-apis.appspot. com/urthecast/map-tiles/rgb/3/
4/3?cloud_coverage_lte=100& acquired_gte=2000-09-01T00:00:
00Z&acquired_lte=2015-09- 01T00:00:z00Z
>
> https://tile-c.urthecast.com/ v1/rgb/3/4/3?&api_key= BAD04ABC498549E3B3CF&api_
secret= 081547A210CA4369B9A69D69E3753D 6D&cloud_coverage_lte=100&
acquired_gte=2000-09-01T00:00: 00Z&acquired_lte=2015-09- 01T00:00:z00Z
>
> The first one doesn't seem to correspond with its zoom level (3) :(
>
> —
> Reply to this email directly or view it on GitHub
> < https://github.com/wri/gfw- api/issues/241 >.
>
—
Reply to this email directly or view it on GitHub .




David González
Vizzuality
C/. Eloy Gonzalo, 27 2º Puerta 7 - 28010 MADRID
M. +34 609125183
skype: david.gonzalez.camara
www.vizzuality.com

**Comment by d4weed** [comment]
looked now and it's even more strange

api shows this 
![image](https://cloud.githubusercontent.com/assets/1506306/10314057/183da888-6c53-11e5-9502-04d19e313607.png)

which is obviously not a zoom 3 tile in rgb, urthecast times out

**Comment by apercas** [comment]
That's not even the RGB renderer :/

**Comment by apercas** [comment]
Hi, we've found another mismatch with http://uc.gfw-apis.appspot.com/urthecast/map-tiles/rgb/9/284/221?cloud_coverage_lte=40&acquired_gte=2015-07-12T00:00:00Z&acquired_lte=2015-10-13T00:00:z00Z and its correspondent with Urthecast here https://tile-c.urthecast.com/v1/rgb/9/284/221?&api_key=BAD04ABC498549E3B3CF&api_secret=081547A210CA4369B9A69D69E3753D6D&cloud_coverage_lte=40&acquired_gte=2015-07-12T00:00:00Z&acquired_lte=2015-10-13T00:00:z00Z

Hope this info could help.
